dataset:
  images:
    type: tiff
    extension: _data.tif
    directory: train
  labels:
    extension: _mask.png
    type: tiff
    directory: labels
  classes:
    - 0:
        name: Shadow
        color: 0x000000
    - 1:
        name: Shadow over Water
        color: 0x000080
    - 2:
        name: Water
        color: 0x0000FF
    - 3:
        name: Snow
        color: 0x00FFFF
    - 4:
        name: Land
        color: 0x808080
    - 5:
        name: Cloud
        color: 0xFFFFFF
    - 6:
        name: Flooded
        color: 0x808000

io:
  tile_size: [512, 512]

train:
  loss: sparse_categorical_crossentropy
  metrics:
    - sparse_categorical_accuracy
  network:
    model:
      layers:
       - Input:
           shape: [~, ~, num_bands]
       - Conv2D:
            filters: 16
            kernel_size: [3, 3]
            padding: same
       - BatchNormalization:
       - Activation:
           activation: relu
           name: c1
       - Dropout:
           rate: 0.2
       - MaxPool2D:
       - Conv2D:
            filters: 32
            kernel_size: [3, 3]
            padding: same
       - BatchNormalization:
       - Activation:
           activation: relu
           name: c2
       - Dropout:
           rate: 0.2
       - MaxPool2D:
       - Conv2D:
            filters: 64
            kernel_size: [3, 3]
            padding: same
       - BatchNormalization:
       - Activation:
           activation: relu
           name: c3
       - Dropout:
           rate: 0.2
       - MaxPool2D:
       - Conv2D:
            filters: 128
            kernel_size: [3, 3]
            padding: same
       - BatchNormalization:
       - Activation:
           activation: relu
           name: c4
       - UpSampling2D:
       - Conv2D:
            filters: 64
            kernel_size: [2, 2]
            padding: same
       - BatchNormalization:
       - Activation:
           activation: relu
           name: u3
       - Concatenate:
           inputs: [c3, u3]
       - Dropout:
           rate: 0.2
       - Conv2D:
            filters: 64
            kernel_size: [3, 3]
            padding: same
       - UpSampling2D:
       - Conv2D:
            filters: 32
            kernel_size: [2, 2]
            padding: same
       - BatchNormalization:
       - Activation:
           activation: relu
           name: u2
       - Concatenate:
           inputs: [c2, u2]
       - Dropout:
           rate: 0.2
       - Conv2D:
            filters: 32
            kernel_size: [3, 3]
            padding: same
       - UpSampling2D:
       - Conv2D:
            filters: 16
            kernel_size: [2, 2]
            padding: same
       - BatchNormalization:
       - Activation:
           activation: relu
           name: u1
       - Concatenate:
           inputs: [c1, u1]
       - Dropout:
           rate: 0.2
       - Conv2D:
           filters: 7
           kernel_size: [3, 3]
           activation: linear
           padding: same
       - Softmax:
           axis: 3
  batch_size: 10
  epochs: 10
  validation:
    from_training: false
    images:
      type: tiff
      extension: _data.tif
      directory: validate
    labels:
      extension: _mask.png
      type: tiff
      directory: labels

mlflow:
  experiment_name: Landsat8 Clouds Example
