#!/usr/bin/env python3

import tensorflow as tf
from argparse import ArgumentParser
import h5py
import pathlib
from delta.config.extensions import custom_objects
import delta.extensions
from delta.ml.io import print_network

parser = ArgumentParser(description='Converts a neural network in a *.h5 file to the DELTA configuration langauge')
parser.add_argument('model_name', type=pathlib.Path, help='The model to convert')
parser.add_argument('-s', '--size', type=str, help='Tile width.')

args = parser.parse_args()

if args.size is not None:
    t = args.size.split('x')
    assert len(t) == 2
    args.size = (int(t[0]), int(t[1]))

print('Configuration File')
with h5py.File(args.model_name, 'r') as f:
    if 'delta' not in f.attrs:
        print(' - Not Available\n')
    else:
        print('\n' + f.attrs['delta'] + '\n')

print('Network')
a = tf.keras.models.load_model(args.model_name, custom_objects=custom_objects(), compile=False)
print_network(a, args.size)
